# CI: lint, test, optional docker build
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint (black + flake8)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install linters and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==23.9.1 flake8==6.1.0
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run black (check)
        run: black --check .
      - name: Run flake8
        run: flake8

  test:
    name: Tests / Smoke
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests or smoke tests
        run: |
          # Prefer pytest if tests exist, otherwise run scripts/smoke_test.py if present
          if [ -d tests ] || ls *_test.py 1> /dev/null 2>&1; then
            python -m pip install pytest
            pytest -q
          elif [ -f scripts/smoke_test.py ]; then
            python scripts/smoke_test.py
          else
            echo "No tests found, skipping test step"
          fi

  docker_build:
    name: Build & Push Docker image (optional)
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && (secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD)
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/pneumonia:latest
            ${{ secrets.DOCKER_USERNAME }}/pneumonia:${{ github.sha }}

# Notes:
# - The docker_build job runs only on pushes to main and only when DOCKER_USERNAME and DOCKER_PASSWORD are set in repository secrets.
# - You can set DOCKER_USERNAME/DOCKER_PASSWORD for Docker Hub, or use a different registry by adapting the tags/login step.
# - The workflow installs requirements.txt when present; adjust python-version and tool versions as needed.
